ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

ARG DEBIAN_FRONTEND=noninteractive

# Install ROS2
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  curl gnupg2 lsb-release python3-pip vim wget build-essential ca-certificates git


### Install Packages
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  python3-argcomplete python3-colcon-common-extensions python3-rosdep \
  qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev

### Install custom packages
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  ros-${ROS_DISTRO}-rqt ros-${ROS_DISTRO}-rqt-* ros-${ROS_DISTRO}-rviz


RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
